import type { ResourceListItemData } from '@/features/resources/types'

export type GeospatialCopImpactedAssetSector =
  | 'Energy'
  | 'Transportation'
  | 'Defense'
  | 'Food'

export type GeospatialCopImpactedAssetRecord = ResourceListItemData & {
  sector: GeospatialCopImpactedAssetSector
  copMapKey: string
}

export const GEOSPATIAL_COP_IMPACTED_ASSET_SECTORS: GeospatialCopImpactedAssetSector[] = [
  'Energy',
  'Transportation',
  'Defense',
  'Food',
]

const COP_WORKSPACE_LABEL = 'Port of Houston Outage'

function asset(
  record: Omit<
    GeospatialCopImpactedAssetRecord,
    | 'deploymentKind'
    | 'assignedWorkspaceId'
    | 'assignedWorkspaceKind'
    | 'assignedIncidentName'
    | 'assignedExerciseName'
    | 'orgChartReportsTo'
    | 'orgChartSortOrder'
    | 'ics204DocumentId'
    | 'pointOfContactMemberId'
    | 'assetCheckInStatus'
    | 'competencyFunction'
    | 'areaKey'
  > & { areaKey?: GeospatialCopImpactedAssetRecord['areaKey'] }
): GeospatialCopImpactedAssetRecord {
  return {
    deploymentKind: 'incident',
    assignedWorkspaceId: null,
    assignedWorkspaceKind: null,
    assignedIncidentName: COP_WORKSPACE_LABEL,
    assignedExerciseName: null,
    orgChartReportsTo: null,
    orgChartSortOrder: 0,
    ics204DocumentId: null,
    pointOfContactMemberId: null,
    assetCheckInStatus: null,
    competencyFunction: null,
    areaKey: record.areaKey ?? 'atlantic',
    ...record,
  }
}

export const GEOSPATIAL_COP_IMPACTED_ASSETS: GeospatialCopImpactedAssetRecord[] = [
  asset({
    copMapKey: 'geospatial-cop-asset-bayport-export',
    assetKey: 'cop-bayport-export',
    id: 901,
    sector: 'Energy',
    name: 'Bayport Export Terminal',
    assetStatus: 'PMC',
    assetStatusUpdatedAt: '04/26/2026 14:10 CDT',
    owner: 'Enterprise Products',
    status: 'Assigned',
    type: 'NGL / LPG Export Terminal',
    teamLead: 'Terminal Superintendent — R. Delgado',
    eta: 'On-site',
    location: 'Bayport Terminal · Houston Ship Channel',
    notes:
      'Loadout curtailment due to substation outage; vapor recovery on manual control; USCG marine safety unit on scene.',
    mapLocation: [-95.023, 29.612],
    currentLocation: 'Bayport Terminal · Pasadena TX',
    datetimeOrdered: '04/26/2026 06:30 CDT',
    opcon: 'Port Houston Unified Command',
    tacon: 'Enterprise Products Operations',
    pointOfContact: 'Terminal Ops (713-555-0142)',
    owningOrganization: 'Enterprise Products',
    quantity: 1,
    unitType: 'terminal',
    unitName: 'Bayport Export Terminal',
    hullTailNumber: 'BPT-EXP-01',
    symbology: 'Energy terminal',
    latitude: '29.612',
    longitude: '-95.023',
    capabilities: 'NGL/LPG loadout; vapor recovery; marine berth transfer',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'Manual loadout curtailment — outage response',
    nextOpPeriodAssignment: 'Restore automated loadout post substation feed',
    checkInStatus: 'Onsite',
    costUnitType: 'per day',
    costPerUnit: 42000,
  }),
  asset({
    copMapKey: 'geospatial-cop-asset-centerpoint-sub',
    assetKey: 'cop-centerpoint-sub',
    id: 902,
    sector: 'Energy',
    name: 'Barbours Cut Substation T-14',
    assetStatus: 'NMC',
    assetStatusUpdatedAt: '04/26/2026 14:22 CDT',
    owner: 'CenterPoint Energy',
    status: 'Assigned',
    type: '138 kV Transmission Substation',
    teamLead: 'Grid Ops — M. Whitaker',
    eta: 'Restoration in progress',
    location: 'Barbours Cut · Port of Houston',
    notes:
      'Primary feed interrupted 06:08 CDT; restoration crew staged; impacts container crane aux power.',
    mapLocation: [-95.019, 29.605],
    currentLocation: 'Barbours Cut Terminal · La Porte TX',
    datetimeOrdered: '04/26/2026 06:12 CDT',
    opcon: 'CenterPoint Energy Grid Ops',
    tacon: 'Port Houston Emergency Support',
    pointOfContact: 'Grid Ops Desk (713-555-0198)',
    owningOrganization: 'CenterPoint Energy',
    quantity: 1,
    unitType: 'substation',
    unitName: 'Barbours Cut T-14',
    hullTailNumber: 'T-14',
    symbology: 'Power infrastructure',
    latitude: '29.605',
    longitude: '-95.019',
    capabilities: '138 kV feed to Barbours Cut terminal aux loads',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'Emergency restoration — partial feed online',
    nextOpPeriodAssignment: 'Full redundancy validation',
    checkInStatus: 'Onsite',
    costUnitType: 'per hour',
    costPerUnit: 8500,
  }),
  asset({
    copMapKey: 'geospatial-cop-asset-mplx-terminal',
    assetKey: 'cop-mplx-terminal',
    id: 903,
    sector: 'Energy',
    name: 'MPLX Ship Channel Terminal',
    assetStatus: 'PMC',
    assetStatusUpdatedAt: '04/26/2026 13:48 CDT',
    owner: 'MPLX Pipeline Operations',
    status: 'Staged',
    type: 'Marine Terminal / Pipeline Manifold',
    teamLead: 'Marine Superintendent — K. Ortega',
    eta: 'Standby',
    location: 'Houston Ship Channel · Galena Park',
    notes:
      'Transfer suspended pending power verification; boom and firewatch teams remain on station.',
    mapLocation: [-95.168, 29.678],
    currentLocation: 'Galena Park Marine Terminal TX',
    datetimeOrdered: '04/26/2026 07:00 CDT',
    opcon: 'MPLX Pipeline Operations',
    tacon: 'USCG Sector Houston-Galveston',
    pointOfContact: 'Marine Superintendent (281-555-0133)',
    owningOrganization: 'MPLX Pipeline Operations',
    quantity: 1,
    unitType: 'terminal',
    unitName: 'Ship Channel Manifold',
    hullTailNumber: 'MPLX-SC-04',
    symbology: 'Pipeline marine terminal',
    latitude: '29.678',
    longitude: '-95.168',
    capabilities: 'Pipeline receipt; marine transfer; firewatch',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'Suspended transfer — outage hold',
    nextOpPeriodAssignment: 'Phased restart after power verification',
    checkInStatus: 'Staged',
    costUnitType: 'per day',
    costPerUnit: 28000,
  }),
  asset({
    copMapKey: 'geospatial-cop-asset-barbours-container',
    assetKey: 'cop-barbours-container',
    id: 904,
    sector: 'Transportation',
    name: 'Barbours Cut Container Terminal',
    assetStatus: 'PMC',
    assetStatusUpdatedAt: '04/26/2026 14:05 CDT',
    owner: 'Port Houston',
    status: 'Assigned',
    type: 'Container Terminal / STS Cranes',
    teamLead: 'Terminal Manager — A. Nguyen',
    eta: 'On-site',
    location: 'Barbours Cut · Port of Houston',
    notes:
      'Gate automation offline; manual truck processing at 40% throughput; 1,240 TEU dwell on terminal.',
    mapLocation: [-95.014, 29.608],
    currentLocation: 'Barbours Cut Container Terminal TX',
    datetimeOrdered: '04/26/2026 06:15 CDT',
    opcon: 'Port Houston',
    tacon: 'Barbours Cut Terminal Ops',
    pointOfContact: 'Terminal Manager (713-555-0167)',
    owningOrganization: 'Port Houston',
    quantity: 4,
    unitType: 'crane',
    unitName: 'STS Crane Battery 2',
    hullTailNumber: 'STS-BC2',
    symbology: 'Container terminal',
    latitude: '29.608',
    longitude: '-95.014',
    capabilities: 'Container load/discharge; truck gate processing',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'Manual gate ops — 40% throughput',
    nextOpPeriodAssignment: 'Restore automation after substation feed',
    checkInStatus: 'Onsite',
    costUnitType: 'per day',
    costPerUnit: 65000,
  }),
  asset({
    copMapKey: 'geospatial-cop-asset-vts-houston',
    assetKey: 'cop-vts-houston',
    id: 905,
    sector: 'Transportation',
    name: 'VTS Houston Command Post',
    assetStatus: 'FMC',
    assetStatusUpdatedAt: '04/26/2026 14:18 CDT',
    owner: 'USCG VTS Houston',
    status: 'Assigned',
    type: 'Vessel Traffic Service',
    teamLead: 'VTS Supervisor — LCDR S. Patel',
    eta: 'On-site',
    location: 'Morgan\'s Point · Houston Ship Channel',
    notes:
      'Managing one-way inbound traffic; AIS correlation active for queue management and pilot scheduling.',
    mapLocation: [-94.978, 29.568],
    currentLocation: 'USCG VTS Houston · Morgan\'s Point TX',
    datetimeOrdered: '04/26/2026 06:00 CDT',
    opcon: 'USCG Sector Houston-Galveston',
    tacon: 'USCG VTS Houston',
    pointOfContact: 'VTS Watch (281-555-0174)',
    owningOrganization: 'U.S. Coast Guard',
    quantity: 1,
    unitType: 'command',
    unitName: 'VTS Houston Command Post',
    hullTailNumber: 'VTS-HOU',
    symbology: 'VTS command',
    latitude: '29.568',
    longitude: '-94.978',
    capabilities: 'Vessel traffic management; AIS correlation; pilot scheduling',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'One-way inbound traffic management',
    nextOpPeriodAssignment: 'Resume two-way traffic post outage',
    checkInStatus: 'Onsite',
    costUnitType: 'per day',
    costPerUnit: 12000,
  }),
  asset({
    copMapKey: 'geospatial-cop-asset-msst-houston',
    assetKey: 'cop-msst-houston',
    id: 906,
    sector: 'Defense',
    name: 'MSST Houston Staging Element',
    assetStatus: 'FMC',
    assetStatusUpdatedAt: '04/26/2026 12:40 CDT',
    owner: 'U.S. Coast Guard MSST Houston',
    status: 'Staged',
    type: 'Maritime Security Response Team',
    teamLead: 'DTRT — CWO J. Ramirez',
    eta: '45 min',
    location: 'Coast Guard Station Houston · Ship Channel',
    notes:
      'Staged for port security augmentation and critical facility escort during outage recovery window.',
    mapLocation: [-95.118, 29.642],
    currentLocation: 'Coast Guard Station Houston TX',
    datetimeOrdered: '04/26/2026 08:30 CDT',
    opcon: 'USCG Sector Houston-Galveston',
    tacon: 'MSST Houston',
    pointOfContact: 'MSST Ops (281-555-0188)',
    owningOrganization: 'U.S. Coast Guard',
    quantity: 1,
    unitType: 'team',
    unitName: 'MSST Houston Staging Element',
    hullTailNumber: 'MSST-HOU',
    symbology: 'Maritime security team',
    latitude: '29.642',
    longitude: '-95.118',
    capabilities: 'Port security augmentation; critical facility escort',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'Staged security augmentation',
    nextOpPeriodAssignment: 'Demobilize post UC release',
    checkInStatus: 'Staged',
    costUnitType: 'per day',
    costPerUnit: 18500,
  }),
  asset({
    copMapKey: 'geospatial-cop-asset-navy-berth',
    assetKey: 'cop-navy-berth',
    id: 907,
    sector: 'Defense',
    name: 'Navy Reserve Fleet Berth 12',
    assetStatus: 'FMC',
    assetStatusUpdatedAt: '04/26/2026 11:15 CDT',
    owner: 'MARAD · Texas Reserve Fleet',
    status: 'Available',
    type: 'Reserve Fleet Mooring',
    teamLead: 'Fleet Manager — C. Brooks',
    eta: 'On-site',
    location: 'Green Cove · Buffalo Bayou',
    notes:
      'Berth power isolated as precaution; no reserve vessels underway; liaison to Port Houston security.',
    mapLocation: [-95.258, 29.702],
    currentLocation: 'Green Cove · Buffalo Bayou TX',
    datetimeOrdered: '04/26/2026 07:45 CDT',
    opcon: 'MARAD',
    tacon: 'Texas Reserve Fleet',
    pointOfContact: 'Fleet Manager (713-555-0120)',
    owningOrganization: 'MARAD',
    quantity: 1,
    unitType: 'berth',
    unitName: 'Reserve Fleet Berth 12',
    hullTailNumber: 'RF-B12',
    symbology: 'Reserve fleet mooring',
    latitude: '29.702',
    longitude: '-95.258',
    capabilities: 'Reserve fleet mooring; shore power isolation',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'Precautionary power isolation',
    nextOpPeriodAssignment: 'Normal ops resume with grid stability',
    checkInStatus: 'Onsite',
    costUnitType: 'per day',
    costPerUnit: 3200,
  }),
  asset({
    copMapKey: 'geospatial-cop-asset-grainger-cold',
    assetKey: 'cop-grainger-cold',
    id: 908,
    sector: 'Food',
    name: 'Grainger Cold Storage Unit 3',
    assetStatus: 'PMC',
    assetStatusUpdatedAt: '04/26/2026 13:30 CDT',
    owner: 'Grainger Cold Logistics',
    status: 'Assigned',
    type: 'Refrigerated Warehouse',
    teamLead: 'Facility Manager — L. Chen',
    eta: 'On-site',
    location: 'Port Terminal Rd · Port of Houston',
    notes:
      'Generator runtime limited to 18h reserve; USDA inspection hold on export poultry pending temp log review.',
    mapLocation: [-95.198, 29.698],
    currentLocation: 'Port Terminal Rd · Houston TX',
    datetimeOrdered: '04/26/2026 06:45 CDT',
    opcon: 'Port Houston Logistics Cell',
    tacon: 'Grainger Cold Logistics',
    pointOfContact: 'Facility Manager (713-555-0155)',
    owningOrganization: 'Grainger Cold Logistics',
    quantity: 1,
    unitType: 'warehouse',
    unitName: 'Cold Storage Unit 3',
    hullTailNumber: 'GCS-U3',
    symbology: 'Cold storage',
    latitude: '29.698',
    longitude: '-95.198',
    capabilities: 'Refrigerated storage; export staging; generator backup',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'Generator backup — USDA hold',
    nextOpPeriodAssignment: 'Release hold after temp log review',
    checkInStatus: 'Onsite',
    costUnitType: 'per day',
    costPerUnit: 8900,
  }),
  asset({
    copMapKey: 'geospatial-cop-asset-grain-elevator',
    assetKey: 'cop-grain-elevator',
    id: 909,
    sector: 'Food',
    name: 'Port Terminal Grain Elevator 12',
    assetStatus: 'PMC',
    assetStatusUpdatedAt: '04/26/2026 13:55 CDT',
    owner: 'Port Houston · Agribusiness Terminal',
    status: 'Staged',
    type: 'Grain Elevator / Loadout',
    teamLead: 'Elevator Superintendent — D. Walsh',
    eta: 'Standby',
    location: 'Port Terminal · Houston Ship Channel',
    notes:
      'Loadout paused; 62k MT corn and 41k MT soybeans awaiting belt power restoration.',
    mapLocation: [-95.228, 29.708],
    currentLocation: 'Port Terminal Grain Elevator 12 TX',
    datetimeOrdered: '04/26/2026 07:10 CDT',
    opcon: 'Port Houston',
    tacon: 'Agribusiness Terminal Ops',
    pointOfContact: 'Elevator Superintendent (713-555-0171)',
    owningOrganization: 'Port Houston',
    quantity: 1,
    unitType: 'elevator',
    unitName: 'Grain Elevator 12',
    hullTailNumber: 'GE-12',
    symbology: 'Grain elevator',
    latitude: '29.708',
    longitude: '-95.228',
    capabilities: 'Bulk grain storage; belt loadout; vessel loading',
    currentOpPeriod: 'OP 1',
    nextOpPeriod: 'OP 2',
    currentOpPeriodAssignment: 'Loadout paused — power restoration',
    nextOpPeriodAssignment: 'Clear export backlog post restart',
    checkInStatus: 'Staged',
    costUnitType: 'per day',
    costPerUnit: 14500,
  }),
]

export function filterGeospatialCopImpactedAssetsBySector(
  assets: GeospatialCopImpactedAssetRecord[],
  sectors: GeospatialCopImpactedAssetSector[]
): GeospatialCopImpactedAssetRecord[] {
  if (sectors.length === 0) {
    return assets
  }
  return assets.filter((asset) => sectors.includes(asset.sector))
}
