export const ICS204A_FIELD_LABELS = {
  incidentName: '1. Incident Name',
  incidentLocation: '2. Incident Location',
  operationalPeriod: '3. Operational Period (Date/Time)',
  operationalPeriodFrom: 'From',
  operationalPeriodTo: 'To',
  branch: '4. Branch',
  divisionGroup: '5. Division / Group',
  resourceIdentifier: '6. Strike Team / Task Force / Resource',
  leader: '7. Leader',
  assignmentLocation: '8. Assignment Location',
  workAssignmentSpecialInstructions:
    '9. Work Assignment Special Instructions, Special Equipment / Supplies, Environmental & Site Safety Considerations',
  siteSafetyPlanLocation: '10. Site Safety Plan located at',
  otherAttachments: '11. Other Attachments (as needed)',
  mapChart: 'Map / Chart',
  weatherForecast: 'Weather Forecast',
  tidesCurrents: 'Tides / Currents',
  otherAttachmentNotes: 'Additional attachments',
  preparedBy: '12. Prepared by',
  reviewedByPsc: '13. Reviewed by (PSC)',
  reviewedByOscIsc: '14. Reviewed by (OSC/ISC)',
  dateTime: 'Date/Time',
  name: 'Name',
} as const
